#ifndef JDA_GLOBALS_H
#define JDA_GLOBALS_H

enum {
    /* Error messages */
    MSG_ERROR = 0,
    MSG_EXCLAMATION = 1,
    MSG_OUT_OF_MEMORY = 2,
    MSG_ZERO_LENGTH_NUMBER = 3,
    MSG_ZERO_LENGTH_STRING = 4,
    MSG_ARGUMENT_EXPECTED = 5,
    /* Built-in documentation */
    MSG_MANUAL_TEST = 6,
    MSG_MANUAL_STACKDUMP = 7,
    MSG_MANUAL_INFO = 8,
    MSG_MANUAL_CLEAR = 9,
    MSG_MANUAL_DUMP = 10,
    MSG_MANUAL_LOGOUT = 11,
    MSG_MANUAL_GETMAIN = 12,
    MSG_MANUAL_RESIZEMAIN = 13,
    MSG_MANUAL_FREEMAIN = 14,
    MSG_MANUAL_PUSH = 15,
    MSG_MANUAL_POP = 16,
    MSG_MANUAL_DUP = 17,
    MSG_MANUAL_INPUT = 18,
    MSG_MANUAL_PRINT = 19,
    MSG_MANUAL_STRING = 20,
    MSG_MANUAL_HELP = 21,
    MSG_MANUAL_LIST = 22,
    MSG_MANUAL_MKCAT = 23,
    MSG_MANUAL_CURRID = 24,
    MSG_MANUAL_USERNAME = 25,
    MSG_MANUAL_EXEC = 26,
    MSG_MANUAL_OPENFILE = 27,
    MSG_MANUAL_NEWFILE = 28,
    MSG_MANUAL_PGM = 29,
    /* Misc messages */
    MSG_TOP_SCREEN = 30,
    MSG_CURR_LOGIN = 31,
    MSG_EMPTY_DATASET = 32,
    MSG_DATASET_EXPECTED = 33,
    MSG_CANT_FIND_DATASET = 34,
    MSG_INVALID_FD = 35,
    MSG_HINT_HELP = 36,
    MSG_MANUAL_NUMBER = 37,
    MSG_MANUAL_SEQPGM = 38,
    MSG_MANUAL_SQRT = 39,
    MSG_MANUAL_FACTORIAL = 40,
    
    /* Unused */
    MSG_POINTER_EXPECTED,
    MSG_INTEGER_EXPECTED,
    MSG_NUMBER_EXPECTED,
    MSG_FAILURE_ON_CALL,
};

extern const char *g_msg[64];

#endif
